name: Deploy to Dev EC2
# It is CD workflow which runs when push event is triggered

# On envent push request on main branch
'on':
  push:
    branches:
      - main 

# Run this job. Job is deploy on EC2.
jobs:
  redeploy_everything:
    name: Deploying every process on dev EC2
    #Github runner VM uses ubuntu OS
    runs-on: ubuntu-latest

    steps:
      # I think there is no need to clone repo on gihub vm cause gihub VM is ssh into our vm to deploy updated branch
      # - name: Checkout the code
      #   #clone the repo on runer VM
      #   uses: actions/checkout@v2

      - name: executing remote ssh commands using key
        #DO SSH from runner VM to our Dev EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.207.212.160 
          username: ubuntu
          key: ${{secrets.SSHPRIVATEKEY}}
          port: 22
          #Runs these commands on my EC2
          script: |
        
           cd ~/week25_turborepo
           git pull origin main

           /home/ubuntu/.bun/bin/bun install
           rm -rf apps/next-app/.next
           /home/ubuntu/.bun/bin/bun run build 
           
            ls apps/next-app/.next/BUILD_ID && echo "✅ Build exists" || echo "❌ Build missing"
           /home/ubuntu/.bun/bin/pm2 restart next-server
           /home/ubuntu/.bun/bin/pm2 restart ws-server
           /home/ubuntu/.bun/bin/pm2 restart http-server

# the error we encountering was because This is usually not because Bun or PM2 aren't installed. It's because the SSH Action runs a non-interactive shell, which does not load your .bashrc and therefore doesn't add Bun's bin directory to PATH.